self.meta = [
      ['Account', ['AccountNumber', 'Account_Potential_Score__c', 'Account_Potential_Score_Formula__c',
                   'Account_Subscription_Plan__c', 'Alexa_Rank__c', 'AllowancePeriod__c', 'AnnualRevenue',
                   'Assigned_SOC2__c', 'BillingCity', 'BillingCountry', 'BillingPostalCode', 'BillingState',
                   'BillingStreet', 'CreatedDate', 'CurrentInPOC__c', 'Customer_MBOs__c', 'datahugapps__Domain__c',
                   'datahugapps__HugRank__c', 'Decision_Maker_Country__c', 'Engagement_Status__c',
                   'Hierarchy_Market_Segment__c', 'Id', 'Industry', 'IsDeleted', 'Is_Ultimate_Parent__c',
                   'LastModifiedDate', 'Launch_Manager__c', 'Market_Segment__c', 'Monthly_Unique_Visitors__c', 'MRR__c',
                   'NAICS_Description__c', 'Name', 'NumberOfEmployees', 'OwnerId', 'ParentId',
                   'Partnership_Program_Status__c', 'Partner_Type__c', 'Primary_NAICS_Code__c',
                   'Primary_Solutions_Partner__c', 'recurly__Account_Code__c', 'recurly__Plan_Code__c',
                   'recurly__Subscriber__c', 'Region__c', 'SP_Partner_Maturity__c', 'Subindustry__c', 'TC_2016__c',
                   'TC_Hierarchy__c', 'Team_Member_1__c', 'Team_Member_1_Email__c', 'Team_Member_1_First_Name__c',
                   'Team_Member_1_Last_Name__c', 'Team_Member_2__c', 'Team_Member_2_Email__c',
                   'Team_Member_2_First_Name__c', 'Team_Member_2_Last_Name__c', 'Team_Member_3__c', 'Team_Member_4__c',
                   'Team_Member_4_Email__c', 'Team_Member_4_First_Name__c', 'Team_Member_4_Last_Name__c',
                   'Team_Member_5__c', 'Technical_Acct_Manager__c', 'Technology_Partner_Status__c',
                   'Total_MRR_Across_Subscriptions__c', 'Total_Won_Opportunities__c', 'TP_Partner_Maturity__c', 'Type',
                   'Ultimate_Parent_Account_ID__c', 'Vertical__c', 'Website', 'Zendesk_Flag_Churn_Risk__c',
                   'Zendesk_Special_Flags__c', 'Zendesk_Tag_AccountPlan__c', 'Zendesk_Tag_Assigned_SA__c',
                   'Zendesk_Tag_Domain__c', 'Zendesk_Tag_Region__c', 'Zendesk__Zendesk_Organization_Id__c',
                   'RecordTypeId', 'Global_Region__c', 'Global_Subregion__c', 'Market_Tier__c',
                   'Ultimate_Market_Sub_Segment__c']],
      ['Lead', ['Account_Potential_Score__c', 'Alexa_Enrichment_Completed__c', 'Android_Interest__c', 'arank__c',
                'BuiltWith_Enrichment_Completed__c', 'Company', 'ConvertedAccountId', 'ConvertedContactId',
                'ConvertedDate', 'ConvertedOpportunityId', 'Country', 'CreatedDate', 'Email',
                'First_Project_Channel__c', 'First_MQL_Date_Time__c', 'Id', 'Inbound_Lead_Form_Type__c', 'Industry',
                'Initial_Form_Source__c', 'iOS_Interest__c', 'IsDeleted', 'LastModifiedDate', 'Lead_ID__c',
                'Lead_Source_Category__c', 'Lead_Source_Subcategory__c', 'LeadSource',
                'Market_Segment__c', 'Marketing_Funnel_Stage__c', 'Marketo_ID__c',
                'MixRank_Enrichment_Completed__c', 'mkto2__Inferred_City__c', 'mkto2__Inferred_Country__c',
                'mkto2__Original_Referrer__c', 'mkto2__Original_Search_Engine__c',
                'mkto2__Original_Source_Info__c', 'mkto2__Original_Source_Type__c', 'Mobile_Web_Interest__c', 'MQL__c',
                'MQL_Date__c', 'Name', 'otm_Campaign__c', 'otm_Campaign_First_Touch__c', 'otm_Campaign_History__c',
                'otm_Content__c', 'otm_Keyword__c', 'otm_Medium__c', 'otm_Source__c', 'OwnerId', 'Region__c',
                'SAL_Date__c', 'Salesforce_Acquisition_Program__c', 'SDR_Owner__c',
                'SimilarWeb_Enrichment_Completed__c', 'State__c', 'Status', 'Subindustry__c', 'Sub_Region__c', 'Title',
                'utm_Campaign__c', 'utm_Campaign_First_Touch__c', 'utm_Content__c', 'utm_Keyword__c', 'utm_Medium__c',
                'utm_Source__c', 'Valid_Lead__c', 'Vertical__c', 'Web_Interest__c', 'Global_Market_Segment__c',
                'Global_Market_Subsegment__c', 'Global_Region__c', 'Global_Subregion__c',
                'Monthly_Unique_Visitors__c', 'NumberOfEmployees']],
      ['Campaign', ['ActualCost', 'AmountAllOpportunities', 'AmountWonOpportunities', 'BudgetedCost',
                    'CampaignMemberRecordTypeId', 'CurrencyIsoCode', 'Description', 'EndDate', 'Id', 'IsDeleted',
                    'LastActivityDate', 'LastModifiedById', 'Name', 'NumberOfOpportunities', 'NumberOfWonOpportunities',
                    'OwnerId', 'ParentId', 'StartDate', 'Status', 'Type', 'CreatedDate', 'LastModifiedDate']],
      ['CampaignMember', ['CampaignId', 'CurrencyIsoCode', 'CompanyOrAccount__c', 'ContactId', 'CreatedById',
                          'CreatedDate', 'Description__c', 'Email__c', 'FirstName__c', 'LastName__c',
                          'FirstRespondedDate', 'Id', 'IsDeleted', 'LastModifiedDate', 'LeadId', 'LeadSource__c',
                          'HasResponded', 'Current_Lead_Status_2__c', 'Market_Segment__c', 'MQL_Date__c', 'Region__c',
                          'SAL_Date__c', 'SQL_Date__c', 'Subregion__c', 'Type_of_MQL__c',
                          'Account_Potential_Score__c']],
      ['Project__c', ['Account__c', 'Active_Analytics_Integrations__c', 'Collaborators_Added__c', 'CreatedDate',
                      'Custom_1v1_Results_Review_Session_CSM__c', 'Duration__c', 'First_Experiment_Created_Date__c',
                      'First_Experiment_Launched_Date__c', 'First_Experiment_with_Results_Date__c',
                      'First_Snippet_Installed_Date__c', 'Id', 'Implement_Main_Funnel_Goals_Date__c', 'IsDeleted',
                      'Kickoff_Call_Email_Date__c', 'LastModifiedDate', 'Multiple_Experiments_Created__c', 'Name',
                      'Notes__c', 'Opportunity__c', 'Owner__c', 'Owner_Role__c', 'Platform_Training_Completion_Date__c',
                      'Platform_Training_Enrollment_Date__c', 'Program_Manager__c', 'Project_Completion_Date__c',
                      'Project_Type__c', 'Results_Review_Training_Completion_Date__c',
                      'Results_Review_Training_Enrollment_Date__c', 'Status__c',
                      'Strategy_and_Ideation_Completion_Date__c', 'Strategy_and_Ideation_Enrollment_Date__c',
                      'Subscription__c', 'Survey_Request_Submitted_Date__c', 'TSE_Implementation_Audit_Date__c',
                      'Understand_and_Share_Results_Date__c', 'Understands_Micro_Macro_Goals_Date__c']],
      ['Team__c', [
          'Account_Executive__c', 'CreatedById', 'CreatedDate', 'CurrencyIsoCode', 'Customer_Success_Manager__c',
          'Health__c', 'Id', 'IsDeleted', 'LastModifiedById', 'LastModifiedDate', 'Managed_Region__c', 'MBOs__c',
          'Mobile_Product_Specialist__c', 'MRR_At_Risk__c', 'Name', 'Next_Steps__c', 'Next_Steps_Date__c',
          'Opener__c', 'POC__c', 'Product_Channel__c', 'Solutions_Architect__c', 'Strategic_Consultant__c',
          'Subscription__c']],
      ['Contact', ['AccountId', 'Contact_Status__c', 'CreatedDate', 'Email', 'Experiments_Created_SFDC__c',
                   'First_MQL_Date_Time__c', 'HasOptedOutOfEmail', 'Id', 'IsDeleted', 'LastModifiedDate',
                   'Latest_Zendesk_Ticket__c', 'LeadSource', 'Marketing_Funnel_Stage__c', 'Marketo_ID__c',
                   'Mobile_Acquisition_Campaign__c', 'Mobile_MQL_Date_Time__c', 'Mobile_MQL__c', 'MQL_Date__c', 'Name',
                   'Nurture_Reason__c', 'of_ClosedZD_Tickets_This_Month__c', 'Optimizely_Developer_Certification__c',
                   'Optimizely_Platform_Certification__c', 'otm_Campaign_First_Touch__c', 'otm_Campaign_History__c',
                   'OwnerId', 'P13N_Acquisition_Campaign__c', 'P13N_MQL_Date_Time__c', 'P13N_MQL__c',
                   'Phone', 'Product_User_Role__c', 'Product_User_Role_Last_Updated__c', 'SAL_Date__c',
                   'Salesforce_Acquisition_Program__c', 'SQL_Date__c', 'Title']],
      ['Opportunity', ['Accelerate_Product_Name_zQuote__c', 'AccountId', 'ActivityId__c', 'Advisory_Product_zQuote__c',
                       'Amount', 'Android_Apps__c', 'Annual_Contract_Value__c', 'ARR__c', 'ARR_Change__c',
                       'ARR_Change_USD__c', 'ARR_Email_Format__c', 'ARR_zSub__c', 'Auto_Renew__c', 'AutoRenew_zSub__c',
                       'Billing_Frequency__c', 'Billing_Period_zQuote__c', 'Billing_Period_zSub__c', 'Bookings_Type__c',
                       'Can_we_reference_their_logo__c', 'Cancellation__c', 'Cancellation_Date__c',
                       'Cancellation_Date_zQuote__c', 'Case_Study_Participation__c', 'Change_Effective_Date__c',
                       'Churn_Amount__c', 'Churn_Category__c', 'Churn_Client_Comments__c', 'Churn_Product_Comments__c',
                       'Churn_reason_in_prose_lesson_learned__c', 'Churn_Risk__c', 'Churn_type__c',
                       'Client_Dev_Resources__c', 'CloseDate', 'Contact_Source__c', 'Contract_End_Date2__c',
                       'Contract_Governed_by__c', 'Contract_Term_in_Months__c', 'Converted_MRR_USD__c', 'Country__c',
                       'CreatedById', 'CreatedDate', 'CurrencyIsoCode', 'Data_Driven_Experimentation__c',
                       'Defined_Testing_Process__c', 'Discount_Final__c', 'Discount_zQuote__c',
                       'Education_Product_Name_zQuote__c', 'Executive_sponsorship__c',
                       'Existing_Subscription_End_Date__c', 'Expansion__c', 'Expansion_Category__c',
                       'Expansion_Type__c', 'Full_Stack_ARR_Change__c', 'Full_Stack_MRR__c', 'Full_Stack_MRR_Change__c',
                       'Full_Stack_MRR_Estimate__c', 'Full_Stack_MRR_zQuote__c', 'Full_Stack_MRR_zSub__c',
                       'Full_Stack_Product__c', 'Full_Stack_Product_zQuote__c', 'Full_Stack_Product_zSub__c',
                       'Functional_Roles__c', 'ForecastCategoryName', 'Governing_Agreement_Start_Date__c',
                       'Has_Testing_Roadmap__c', 'High_Value_Touch_Counter__c', 'Hold_Out__c',
                       'Horizontal_Expansion__c', 'Id', 'Initial_Optimization_Focus__c', 'Initial_Term_zQuote__c',
                       'Initial_Term_zSub__c', 'iOS_Apps__c', 'IsDeleted', 'IsWon',
                       'Known_Technical_Business_Concerns__c', 'LastModifiedDate', 'Lead_Conversion_Percentage__c',
                       'Lead_ID__c', 'LeadSource', 'Lead_Source_Category__c', 'Lead_Source_Subcategory__c',
                       'Lost_Reason__c', 'Lost_Reason_Details__c', 'Major_Audience_Segments__c', 'Mobile_ARR_Change__c',
                       'Mobile_MRR__c', 'Mobile_MRR_Change__c', 'Mobile_MRR_Estimate__c', 'Mobile_MRR_zQuote__c',
                       'Mobile_MRR_zSub__c', 'Mobile_Product__c', 'Mobile_Product_zQuote__c', 'Mobile_Product_zSub__c',
                       'Mobile_Properties__c', 'Monthly_Uniques__c', 'MRR__c', 'MRR_Change__c', 'MRR_Email_Format__c',
                       'MRR_zQuote__c', 'MRR_zSub__c', 'Name', 'New_Expansion_MRR__c', 'Next_Steps__c',
                       'Opportunity_Age__c', 'Opportunity_ID_18_Char__c', 'Opportunity_Record_Type_Name__c',
                       'Opportunity_Source__c', 'Original_Source_Info__c', 'otm_Campaign__c', 'otm_Content__c',
                       'otm_Keyword__c', 'otm_Medium__c', 'otm_Source__c', 'OTT_MRR_Estimate__c', 'Overage_Charge__c',
                       'Owner__c', 'OwnerId', 'P13N_ARR_Change__c', 'P13N_MRR__c', 'P13N_MRR_Change__c',
                       'P13N_MRR_Estimate__c', 'P13N_MRR_zQuote__c', 'P13N_MRR_zSub__c', 'P13N_Product__c',
                       'P13N_Product_zQuote__c', 'P13N_Product_zSub__c', 'Package__c', 'Personalization_Package__c',
                       'Personalization_Price__c', 'Personalization_Properties__c', 'Platform_Type__c',
                       'PO_Required__c', 'Primary_Champion__c', 'Primary_Solutions_Partner__c', 'Probability',
                       'Proof_of_Concept_POC__c', 'Properties__c', 'Properties_Price__c', 'Quick_Start_Price__c',
                       'Quickstart_Product_zQuote__c', 'Reach_Price__c', 'Reach_Volume__c',
                       'Recommendations_Impl_Prod_Name_zQuote__c', 'Recommendations_MRR_Estimate__c', 'RecordTypeId',
                       'Renewal_Term_zQuote__c', 'Renewal_Term_zSub__c', 'Sales_Engineer__c', 'Sales_Engineer_Name__c',
                       'SE_Involved__c', 'Snapshot_Manager__c', 'StageName', 'Start_Date_zQuote__c',
                       'Strategy_Org_Readiness_Ranking__c', 'Subscription__c', 'Subscription_End_Date_zSub__c',
                       'Subscription_Level__c', 'Subscription_Start_Date__c', 'Subscription_Start_Date_zSub__c',
                       'Subscription_Term_Setting_Type_zSub__c', 'Subscription_Term_Start_Date_zQuote__c',
                       'Subscription_Term_End_Date_zQuote__c', 'Support_ARR__c', 'Support_ARR_Change__c',
                       'Support_MRR__c', 'Support_MRR_Change__c', 'Support_MRR_zQuote__c', 'Support_MRR_zSub__c',
                       'Support_Tier__c', 'Support_Tier_Upgrade__c', 'Support_Upgrade_Price__c',
                       'Tech_Savvy_Ranking__c', 'Term_End_Date_zSub__c', 'Term_Start_Date_zSub__c',
                       'Testing_ARR_Change__c', 'Testing_ARR_Estimate__c', 'Testing_MRR__c', 'Testing_MRR_Change__c',
                       'Testing_MRR_Estimate__c', 'Testing_MRR_zQuote__c', 'Testing_MRR_zSub__c', 'Testing_Product__c',
                       'Testing_Product_zQuote__c', 'Testing_Product_zSub__c', 'Testing_Properties__c', 'Total_ARR__c',
                       'Total_ARR_Change__c', 'Total_MRR__c', 'Total_MRR_Change__c', 'Traffic_Android_MAUs__c',
                       'Traffic_iOS_MAUs__c', 'Traffic_Web_MUVs__c', 'Travel_Expenses_Product_Name_zQuote__c', 'Type',
                       'utm_Campaign__c', 'utm_Medium__c', 'utm_Source__c', 'Web_Domains__c',
                       'Web_Experimentation_Properties__c']],
      ['Partner', ['AccountFromId', 'AccountToId', 'CreatedById', 'CreatedDate', 'Id', 'IsDeleted', 'IsPrimary',
                   'LastModifiedDate', 'ReversePartnerId', 'Role']],
      ['Event', ['AccountId', 'ActivityDate', 'Activity_Type__c', 'Actual_End_Time__c', 'Actual_Start_Time__c',
                 'CreatedById', 'CreatedDate', 'Description', 'EndDateTime', 'Id', 'IsDeleted', 'Internal__c',
                 'LastModifiedDate',  'Marketing_Initiated__c', 'Objective__c', 'Onsite__c', 'OwnerId', 'Product__c',
                 'Session_Status__c', 'StartDateTime', 'Subject', 'Success_Role__c', 'Task_Minutes__c', 'Task_Tags__c',
                 'Type', 'WhoId', 'Created_By_Role_Snapshot__c']],
      ['Task', ['AccountId', 'ActivityDate', 'Activity_Type__c', 'Actual_End_Time__c', 'Actual_Start_Time__c',
                'CallType', 'CreatedById', 'CreatedDate', 'Description', 'Expansion_Notification__c', 'Id', 'IsDeleted',
                'Internal__c', 'Marketing_Initiated__c', 'Objective__c', 'Onsite__c', 'Opportunity_Created__c',
                'OwnerId', 'Product__c', 'Session_Status__c', 'Status', 'Subject', 'Success_Role__c', 'Task_Minutes__c',
                'Task_Tags__c', 'Type', 'WhoId', 'Created_By_Role_Snapshot__c']],
      ['Trial_Request__c', ['Account_Code__c', 'CreatedById', 'CreatedDate', 'End_Date__c', 'Existing_Account_Notes__c',
                            'Existing_Optimizely_Account__c', 'Extension_Counter__c', 'Id', 'IsDeleted',
                            'InitialProductAdmin_Email__c', 'Justification_Objective__c', 'LastModifiedDate',
                            'Monthly_Uniques__c', 'Name', 'Opportunity__c', 'OwnerId', 'Start_Date__c', 'Status__c']],
      ['User', ['Alias', 'CreatedDate', 'Email', 'Id', 'IsActive', 'LastModifiedDate', 'ManagerId', 'Name',
                'UserRoleId', 'UserType']],
      ['UserRole', ['Id', 'LastModifiedDate', 'Name']],
      ['Customer_Feedback__c', ['Account__c', 'AccountID__c', 'Account_Owner__c', 'Contact__c', 'CreatedById',
                                'CreatedDate', 'Detractor__c', 'Email__c', 'Follow_up_Date__c',
                                'Follow_up_Email_Sent__c', 'Follow_up_Notes__c', 'Follow_up_Owner__c', 'Id',
                                'IsDeleted', 'LastModifiedById', 'LastModifiedDate', 'Lead__c',
                                'Lookup_ContactLead_Email__c', 'Lookup_ContactLeadName__c', 'Meta_Data_Field_1__c',
                                'Meta_Data_Field_2__c', 'Meta_Data_Field_3__c', 'Meta_Data_Field_4__c',
                                'Meta_Data_Field_5__c', 'NPS__c', 'Name', 'NPS_Category__c',
                                'NPS_Reason_Question_Text__c', 'NPS_Score__c', 'NPS_Score_Reason__c', 'OwnerId',
                                'Passive__c', 'Promoter__c', 'Question_10_Text__c', 'Question_10_Value__c',
                                'Question_11_TExt__c', 'Question_11_Value__c',
                                'Question_12_Text__c', 'Question_12_Value__c', 'Question_13_Text__c',
                                'Question_13_Value__c', 'Question_14_Text__c', 'Question_14_Value__c',
                                'Question_15_Text__c', 'Question_15_Value__c', 'Question_16_Text__c',
                                'Question_16_Value__c', 'Question_17_Text__c', 'Question_17_Value__c',
                                'Question_18_Text__c', 'Question_18_Value__c', 'Question_19_Text__c',
                                'Question_19_Value__c', 'Question_1_Text__c', 'Question_1_Value__c',
                                'Question_20_Text__c', 'Question_20_Value__c', 'Question_2_Text__c',
                                'Question_2_Value__c', 'Question_3_Text__c', 'Question_3_Value__c',
                                'Question_4_Value__c', 'Question_4_Text__c', 'Question_5_Text__c',
                                'Question_5_Value__c', 'Question_6_Text__c', 'Question_6_Value__c',
                                'Question_7_Text__c', 'Question_7_Value__c', 'Question_8_Text__c',
                                'Question_8_Value__c', 'Question_9_Text__c', 'Question_9_Value__c', 'RecordTypeId',
                                'Requires_Follow_up__c', 'Survey_Completion_Date_Time__c', 'Survey_Response_Link__c',
                                'Survey_Start_Date_Time__c']],
      ['Li_Community_User1__c', ['Email_Address__c', 'Id', 'IsDeleted', 'First_Name__c', 'Last_Name__c',
                                 'Last_Visit_Date__c', 'Last_Visit_Time__c', 'Lithium_User_Id__c', 'Metric_Logins__c',
                                 'Metric_Messages_Read__c', 'Metric_Minutes_Online__c', 'Metric_Posts__c',
                                 'Name', 'Rank__c', 'Registration_Time__c', 'User_Group_City__c',
                                 'User_Group_Member__c', 'CreatedDate', 'LastModifiedDate']],
      ['Partners_Involved__c', ['Client_Opportunity__c', 'CreatedDate', 'Id', 'IsDeleted', 'LastModifiedDate', 'Name',
                                'Partner_Account__c', 'Partner_Type__c', 'Primary__c', 'Referral__c', 'Referral_Contact__c',
                                'Relationship_Type__c']],
      ['Domain_App__c', ['Channel__c', 'CreatedDate', 'Domain_Account__c', 'Id', 'IsDeleted', 'LastModifiedDate',
                         'Name', 'Opportunity__c']],

      ['Account_to_Mobile_App__c', ['Account__c', 'CreatedDate', 'Id', 'IsDeleted', 'LastModifiedDate',
                                    'Mobile_App__c']],
      ['Lead_to_Mobile_App__c', ['CreatedDate', 'Id', 'IsDeleted', 'LastModifiedDate', 'Lead__c', 'Mobile_App__c']],
      ['Mobile_App__c', ['Active__c', 'App_Store_Link__c', 'Bundle_Id__c', 'Competitor_SDKs_Installed__c',
                         'CreatedDate', 'Devel__c', 'Devel_SDK_Versions__c', 'Genre__c', 'Id', 'IsDeleted',
                         'LastModifiedDate', 'Live__c', 'Live_SDK_Versions__c', 'Partner_SDKs_Installed__c',
                         'Platform__c']],
      ['CurrencyType', ['ConversionRate', 'CreatedDate', 'Id', 'LastModifiedDate', 'DecimalPlaces', 'IsActive',
                        'IsCorporate', 'IsoCode']],
      ['AccountContactRole', ['AccountId', 'ContactId', 'CreatedDate', 'Id', 'IsDeleted', 'IsPrimary',
                              'LastModifiedDate', 'Role']],
      ['AccountTeamMember', ['AccountAccessLevel', 'AccountId', 'CreatedById', 'CreatedDate', 'Id', 'IsDeleted',
                             'LastModifiedById', 'LastModifiedDate', 'TeamMemberRole', 'UserId']],
      ['OpportunityTeamMember', ['CreatedById', 'CreatedDate', 'CurrencyIsoCode', 'Id', 'IsDeleted', 'LastModifiedById',
                                 'LastModifiedDate', 'Name', 'OpportunityAccessLevel', 'OpportunityId',
                                 'TeamMemberRole', 'UserId']],
      ['Subscription__c', ['Account__c', 'Account_Code__c', 'Android_Apps__c', 'Billing_Point_of_Contact__c',
                           'Churn_Amount__c', 'Churn_Risk__c', 'Contract_End_Date__c', 'Contract_Start_Date__c',
                           'CreatedDate', 'CurrencyIsoCode', 'Customer_Health__c', 'Customer_Health_Reasons__c',
                           'Full_Stack_Product_zSub__c', 'Id', 'Initial_Product_Admin_Email__c', 'iOS_Apps__c',
                           'IsDeleted', 'LastModifiedDate', 'Mobile_Product_zSub__c', 'MRR__c',
                           'MRR_Change_Forecast__c', 'Web_Experimentation_MUV_Limit__c', 'OK_to_Reference__c',
                           'Opportunity__c', 'Opportunity_Latest__c', 'Number_of_Teams__c',
                           'P13N_MRR_zSub__c', 'P13N_Product_zSub__c', 'Package__c', 'Plan_Name__c', 'Platform_Type__c',
                           'Primary_Solutions_Partner__c', 'Properties__c', 'Properties_Price__c', 'Reach_Price__c',
                           'Reach_Volume__c', 'Request_Extension__c', 'Recommendations_Product_zSub__c',
                           'Status_zSub__c', 'Subscriber__c', 'Subscription_ID__c',
                           'Subscription_End_Date_zSub__c', 'Support_Tier__c', 'Support_Tier_Upgrade__c',
                           'Support_Upgrade_Price__c', 'Testing_MRR_zSub__c', 'Testing_Product_zSub__c',
                           'Traffic_Android_MAUs__c', 'Traffic_iOS_MAUs__c', 'Traffic_Web_MUVs__c',
                           'Utilization_Country__c', 'Utilization_Region__c', 'VAT_ID__c', 'Web_Domains__c',
                           'Is_Trial_Subscription__c', 'Trial_Start__c', 'Trial_Expiration__c', 'Status__c',
                           'Priority_Support__c', 'New_Optimizely_Migration_Stage__c', 'New_Optimizely_Flag__c',
                           'Trial_Length__c', 'Cold_Account__c', 'Cold_Account_Action__c', 'Cold_Account_Notes__c',
                           'Cold_Account_Reason__c', 'Cold_Status__c', 'AE_Managed__c', 'Cold_Account_Subreason__c']],
      ['DatedConversionRate', ['ConversionRate', 'CreatedDate', 'Id', 'IsoCode', 'LastModifiedDate', 'NextStartDate',
                               'StartDate']],
      ['Property__c', ['Account__c', 'Active__c', 'Channel__c', 'CreatedDate', 'Id', 'IsDeleted', 'LastModifiedDate',
                       'Name']],
      ['Property_to_Opportunity__c', ['Channel__c', 'CreatedDate', 'Domain__c', 'Id', 'IsDeleted', 'LastModifiedDate',
                                      'Opportunity__c']],
      ['Team_Member__c', ['Contact__c', 'CreatedDate', 'Id', 'IsDeleted', 'LastModifiedDate', 'Team__c']],
      ['Product_User__c', ['Contact__c', 'CreatedDate', 'Email__c', 'Id', 'IsDeleted', 'Last_Name__c',
                           'LastModifiedDate', 'Lead__c', 'Plan_ID__c', 'Role__c', 'Subscription__c', 'User_Name__c']],
      ['Certification__c', ['Attempt_Id__c', 'Certification_Type__c', 'Contact__c', 'CreatedDate', 'Email__c', 'Id',
                            'IsDeleted', 'LastModifiedDate', 'Lead__c', 'Status__c']],
      ['RecordType', ['CreatedDate', 'Id', 'IsActive', 'LastModifiedDate', 'Name']],
      ['bizible2__Bizible_Attribution_Touchpoint__c',
          ['Name', 'bizible2__Ad_Campaign_Name__c', 'bizible2__Ad_Group_Name__c', 'bizible2__Ad_Destination_URL__c',
           'bizible2__Browser__c', 'bizible2__Contact__c', 'bizible2__Form_URL_Raw__c', 'bizible2__Geo_City__c',
           'bizible2__Geo_Country__c', 'bizible2__Geo_Region__c', 'bizible2__Keyword_Text__c', 'Id', 'CreatedDate',
           'bizible2__Landing_Page_Raw__c', 'bizible2__Lead__c', 'bizible2__Marketing_Channel__c', 'LastModifiedDate',
           'bizible2__Marketing_Channel_Path__c', 'bizible2__Medium__c', 'bizible2__Placement_Name__c',
           'bizible2__Platform__c', 'bizible2__Referrer_Page_Raw__c', 'bizible2__Search_Phrase__c',
           'bizible2__Site_Name__c', 'bizible2__Touchpoint_Date__c', 'bizible2__Touchpoint_Position__c',
           'bizible2__Touchpoint_Source__c', 'bizible2__Touchpoint_Type__c', 'bizible2__UniqueId__c']],
      ['Competitor__c', ['App_Testing__c', 'CreatedById', 'CreatedDate', 'DW_Competitor_Name__c',
                         'Headquarters__c', 'Id', 'In_Business__c', 'IsDeleted', 'LastModifiedById', 'LastModifiedDate',
                         'Name', 'OTT__c', 'OwnerId', 'Personalization__c', 'Products__c', 'Server_side_Testing__c',
                         'Website__c', 'Web_Testing__c']],
      ['Competitor_Deal__c', ['Account__c', 'Competitor__c', 'Concatenated_Deal_Name__c', 'Contract_End_Date__c',
                              'Created_by_BuiltWith_Sync__c', 'CreatedById', 'CreatedDate', 'Deal_Outcome__c',
                              'Deal_Outcome_Reason_Freeform__c', 'Deal_Outcome_Reason_Picklist__c', 'Deal_Strategy__c',
                              'Id', 'Inactive__c', 'IsDeleted', 'Last_Enriched_Date__c',
                              'LastModifiedDate', 'Opportunity__c', 'Opportunity_Bookings_Type__c',
                              'Opportunity_Stage__c', 'Pricing__c', 'Primary_Competitor__c', 'Relationship_Type__c',
                              'Won_From_Lost_To__c'
                              ]]
    ]
